### ISSUE TITLE
Private repository support.

### ISSUE THREAD

**Issue by hlobil** [tjanczuk/gissues#1]
Is there a technical reason for not supporting private repositories?

Pavel

**Comment by tjanczuk** [comment]
I am planning to support private repositories in the next update of the app.

**Comment by coolaj86** [comment]
+1

Anything I can do to sweeten the deal for you or help get that rolled out faster?

**Comment by errordeveloper** [comment]
Shouldn't be to difficult, right? I'd have a look if you could give me a little pointer :)

**Comment by tjanczuk** [comment]
This is now fixed and online at http://gissues.com. If you were previously logged in with gissues.com you may need to log out and log back in again to refresh your OAuth token.
