### ISSUE TITLE
Tell users that you're adding text to the issue

### ISSUE THREAD

**Issue by christianbundy** [tjanczuk/gissues#13]
I don't remember being told that JSON data was going to be added to the original comment in each issue – it's possible that I just missed something, but I think this is _very_ important for developers to know.

**Comment by daviesgeek** [comment]
PLEASE DO THIS! I didn't know that it would do this; now I have to go edit all my issues and remove the text. Terrible UX

**Comment by Potherca** [comment]
Actually, the README clearly states (since Jan 20, 2012/5d456ff)

> The service modifies the description of your GitHub issues by adding a small textual fragment that captures gissues metadata.

You might want to take a look at #20 which offers an actual solution to the problem of a JSON blob being added to each issue.

**Comment by christianbundy** [comment]
@potherca That would be fine if the source code was the only way of using the product, but seeing as how gissues.com is how people actually _use_ the product, that's the most important place to have this side-effect documented. Please let me know whether I'm missing something in the [views](https://github.com/tjanczuk/gissues/tree/master/src/views).

As it stands, this is like installing a browser extension with an ugly undocumented side-effect, and when you bring it up it's defended by  "_Actually_, the README clearly states..." as if the user was expected to find the source code and look through the README before installing.

You're right that this issue is related to #20, but it's disingenuous to pretend that each and every user is expected to read the README, especially without being prompted by the website.

**Comment by Potherca** [comment]
Fair point. 

As the [gissues is down](http://www.downforeveryoneorjustme.com/gissues.com) at the time of this writing I have had no other option but review things from here. The maintainers' choice of not having separate bug trackers for the code _and_ the service seems a poor one as it causes misunderstandings like this.

My apologies for any discomfort my tone (may have) caused.

**Comment by christianbundy** [comment]
Not a problem at all, I just wanted to make sure that the issue wasn't closed prematurely. I absolutely agree with you though, it's difficult to work with the code that has both internal and external documentation.

**Comment by Potherca** [comment]
The index view (line [99](https://github.com/tjanczuk/gissues/blob/master/src/views/index.ejs#L99)) does state 

> Whiteboard status data is stored within GitHub issue itself

but that does seems to be slightly unclear (both the _what_ and the _how_ have not been clearly stated).

I've added an explanation. Would that be clear enough? (Suggestions for improvement are welcome).

**Comment by Potherca** [comment]
Looks like our efforts may be in vain as the author of this project has stated he is no longer maintaining this project: https://twitter.com/tjanczuk/status/706961368235151360
