### ISSUE TITLE
Bug: Repositories don't show up when no organiziation

### ISSUE THREAD

**Issue by debonet** [tjanczuk/gissues#4]
## Brief description

Could not use app, apparent connection or login failure 
## Procedure:
1. go to gissues.com
2. pick "Go to my public and private repos"
3. When asked for App Authorization click "Allow"
4. See gissues main screen, but no repositories in dropdown list
## Expected:
1. repositories in dropdown list
## Other info:
1. github shows gissues under authorized applications
2. no javascript errors reported by chrome debugger
3. AJAX network request to api.github.com/user/repos seems to have returned a valid repo array
4. AJAX to api.github.com/user/orgs returns [](empty array)
## Other things tried:
1. reloading: no effect/same result
2. log out, log back in: no effect/same result
3. log out, deauthorize app, repeat initial procedure: no effect/same result
4. tried from new browser: same result
## configuration
- OS: Mac OS X 10.6.4
- Browser: Chrome 18.0.1025.113
- Browser2: Safari 5.1 (6534.50)

**Comment by debonet** [comment]
## Update

When I added an organization, gissues now appears to load up my account and repositories properly.

**Comment by tjanczuk** [comment]
Thank you for the detailed report. I believe the bug is in https://github.com/tjanczuk/gissues/blob/master/src/public/gissues.js#L373, whereby if the user does not belong to any organizations (data.length === 0), the list of repositories will not be displayed at all.

**Comment by debonet** [comment]
That looks right. And if you simply change the `data.length > 0` to `data.length >= 0` I _think_ it will work properly.

**Comment by tjanczuk** [comment]
http://gissues.com has been updated with the new bits.
