### ISSUE TITLE
Bug: Sorting not working with large number of issues

### ISSUE THREAD

**Issue by debonet** [tjanczuk/gissues#5]
## Brief description

Sorting within the backlog list does not seem to persist after a reload
## Procedure:
1. log in to gissues.com
2. move an issue from lower down in the backlog to the top of the backlog
3. reload
4. note, moved issue is no longer at top
## Expected:

Moved issue to still be on top
## Other info:
- issue details show @gissues:{"order":} fields appear to be correct, but display is wrong
- order problems happen at other locations, not just top
## configuration
- OS: Mac OS X 10.6.4
- Browser: Chrome 18.0.1025.113

**Comment by tjanczuk** [comment]
If the repo is public, can you point me to one or more issues that do not show up in the right order? I would like to inspect their details more closely.

**Comment by debonet** [comment]
Unfortunately its not. I can post a few of the top items here:
1. @gissues:{"order":32.95454545454545,"status":"backlog"}
2. @gissues:{"order":83.23863636363636,"status":"backlog"}
3. @gissues:{"order":16.477272727272727,"status":"backlog"}
4. @gissues:{"order":82.38636363636363,"status":"backlog"}
5. @gissues:{"order":65.9090909090909,"status":"backlog"}

It does not appear as though they're lexically sorted either (which would have been surprising given that the sorting function uses `-`)

**Comment by tjanczuk** [comment]
Thanks again for reporting this issue. It is now fixed and online at http://gissues.com. 

You may need to wait a few seconds before refreshing the page for the change in issue order to be reflected - it appears that GitHub APIs have some latency in reflecting the latest issue status.

**Comment by debonet** [comment]
Thanks Tomasz!
